### ISSUE TITLE
对接ss报错

### ISSUE THREAD

**Issue by Doklllll** [Misaka-blog/XrayR-script#8]
XrayR[21768]: 2022/06/09 13:42:12 本地ip rejected  common/drain: common/drain: unable to drain connection > EOF > proxy/shadowsocks: failed to read 50 bytes > EOF
刚更新完第一秒可ping通，但马上就寄了，网站上端口可ping通

**Comment by misakano7545** [comment]
建议换协议，ss已经被识别了
